### ISSUE TITLE
Import performance

### ISSUE THREAD

**Issue by aleksijuvani** [gltf-rs/gltf#207]
I'm trying to import a model of the Sponza Atrium, but I'm experiencing some really atrocious import performance. The model has over 300 meshes which results in over 1500 accessors in the glTF file. Importing the model takes several seconds in release mode and an order of magnitude longer in debug mode (it took so long I didn't even bother measuring it).

Profiling seems to indicate that 74 % (or 93 % with a binary model) of the import time is spent inside `gltf::accessor::Accessor::new` and 15 % (18 % with a binary model) is spent inside `gltf::buffer::View::new`.

**Comment by alteous** [comment]
Interesting observations.

Note that the bulk of the 'import' work happens in the `gltf-json` crate. The top-level `gltf` crate is merely a convenience wrapper around the json data structures. This wrapper isn't stress tested (on a side note: this is one reason why I'm hesitant to release 1.0) and some of the performance penalties you mention are likely due to some [lazy shortcuts](https://github.com/gltf-rs/gltf/blob/master/src/accessor/mod.rs#L100) in the implementation.

I'll try to reproduce, get some benchmarks, and report the findings soon.

**Comment by aleksijuvani** [comment]
Thank you! I've uploaded the models I've used for testing [here](https://www.dropbox.com/sh/jq6in50hlqpykhp/AABu4oJgDVT3Xun6equOnbUTa?dl=0).

**Comment by aleksijuvani** [comment]
To be more specific about the circumstances where this occurs, I observed the above by invoking the `read_positions`, `read_normals`, `read_tex_coords` and `read_indices` functions on a primitive reader when looping through each primitive of each mesh in the file.

**Comment by alteous** [comment]
> To be more specific about the circumstances where this occurs, I observed the above by invoking the read_positions, read_normals, read_tex_coords and read_indices functions on a primitive reader when looping through each primitive of each mesh in the file.

Please note these functions are provided for convenience but are not actually intended to be used for real-time import. glTF buffers are designed to be copied directly in GL buffer objects, thus avoiding time-consuming processing of vertex data.

I encourage game developers to manipulate glTF ahead of time so that vertex data (et cetera) is optimised for their particular engine.
