### ISSUE TITLE
[Question] Plans for WebAssembly?

### ISSUE THREAD

**Issue by IcanDivideBy0** [gltf-rs/gltf#211]
Hello,

I'd like to know the current status of WebAssembly support in this library. From what I see it is currently not supported, but it's kind of unclear if it's on purpose or not.

AFAIK GLTF is designed with WebGL in mind (not only but still), and claim to be the JPEG of the 3D. Having this in mind I can't see any reasons that a JPEG decoder should handle file reading. So I belive this lib should rely on a generic `impl Read` instead of reading from the file system. Also for resources references, I think it should be possible to provide some custom loader to the decoder.

What are your thoughts on this? Do you think it would be too much to refactor and starting another GLTF loader with wasm in mind would be a better solution?

**Comment by bwasty** [comment]
It used to work just fine with 0.9.2: https://github.com/gltf-rs/gltf-validator-web.
I don't quite know all the changes since then, but I think the only problem is `gltf::import`, which is actually just a convenience function for loading from a normal file. If you look at it's [implementation](https://github.com/gltf-rs/gltf/blob/master/src/import.rs), you should find the necessary methods that are not file-dependant (`from_reader`, `from_slice`, ...).
That said, I started working on an engine that targets WebAssembly and needs glTF, and I hope I can make some changes for easier import, or at least an example, at the end.

**Comment by bwasty** [comment]
I had another idea: create a separate (wasm-only?) crate on top of `gltf` that uses the new `std::future` API to offer the "same" interface as my [TypeScript glTF Loader](https://github.com/bwasty/gltf-loader-ts), i.e. async functions for loading the initial json, individual buffers/images, or everything at once (`preFetchAll()`).

**Comment by alteous** [comment]
The `import` function is provided for convenience, as @bwasty correctly points out. The documentation should be altered to mention this.

> So I belive this lib should rely on a generic impl Read instead of reading from the file system. 

We've had generic `Read` for [`Document`](https://docs.rs/gltf/0.12.0/gltf/struct.Gltf.html#method.from_reader) and [`Glb`](https://docs.rs/gltf/0.12.0/gltf/binary/struct.Glb.html#method.from_reader) for a while now. These do not read from the file system; resource management is delegated to the user.

> Also for resources references, I think it should be possible to provide some custom loader to the decoder.

We used to have this in [version 0.8](https://docs.rs/gltf/0.8.6/gltf/trait.Source.html). It was removed because (amongst other reasons):
1. It makes error handling awkward.
2. It made the library usage unreasonably complex.
3. The crate was heavily criticised because of (2).
4. The user has less control over the scheduling of downloads, et cetera.

I do see WebAssembly as an important target for the crate and glTF itself but we should think carefully about how to support this use case. Immediately, we could remove the `import` function for WASM. Alternatively, to keep the convenient interface, we could adapt it to take a URL instead of a file path. Writing an asynchronous importer or otherwise would be delegated to the user if deemed necessary.

**Comment by bwasty** [comment]
I haven't gotten to glTF in our new engine yet, but probably soon. I'll first put everything into [`yage-gltf`](https://github.com/bwasty/yage/tree/master/yage-gltf) - when that's working it'll probably be clearer how to make this crate better.

**Comment by dakom** [comment]
I've got a couple functions that wrap web-sys to provide image, text, and arraybuffer loading as native rust futures (0.3, usable with await)

How can I use this with the crate here in order to load gltf and all the assets? Are there any examples using custom loaders?

**Comment by alteous** [comment]
I assume you're attempting to use `gltf` in your crate which is compiled to WASM. You can copy and adapt the [reference `import` implementation](https://github.com/gltf-rs/gltf/blob/master/src/import.rs) to your needs. There are no other examples. I expect you'll need to replace file reads with downloads.

**Comment by dakom** [comment]
from looking at the types of the text and media loaders, it seems that it isn't compatible with async loading (e.g. loading an image via network request)?

**Comment by bwasty** [comment]
No, they're not compatible with async currently. We actually had that before and it was removed because some people complained (-> https://github.com/gltf-rs/gltf/issues/211#issuecomment-485371553). Now that Futures and async are part of Rust maybe we could try it again...
But the current workaround would be to first load everything asynchronously and only call `import_buffer_data` etc. when the data is available.

If you come up with anything working, let us know. I would certainly like to try to make it easy and integrated...I've wanted async loading and WebAssembly from the start :)

**Comment by bwasty** [comment]
Not sure if it helps, but this is how it looked: https://github.com/bwasty/gltf-viewer/blob/master/src/http_source.rs (compatible with 0.8 I guess...I left the file there, but it's dead code at the moment).

**Comment by dakom** [comment]
> But the current workaround would be to first load everything asynchronously and only call import_buffer_data etc. when the data is available.

I guess I'll give it a shot and comment when I get stuck? ;)

**Comment by dakom** [comment]
oh ... wait a sec... I forgot that in GLTF all the buffers and images are in a flat list. This should be straightforward... :)

**Comment by dakom** [comment]
So, after loading the text... Gltf::from_slice() works fine with this: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TriangleWithoutIndices/glTF

But crashes with this: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan/glTF

Not talking about data loading, just the raw string...

**Comment by dakom** [comment]
hah, works fine in firefox o_O
