### ISSUE TITLE
Allow access to Extensions or json data

### ISSUE THREAD

**Issue by sjohnsonaz** [gltf-rs/gltf#226]
I'm attempting to import Light information, but cannot access Extensions.  I saw in other issues that there is some discussion on exactly how to import Extensions.  Is it possible to at least provide json structure access, so that I can read the information myself.  It's currently private in the `Node` struct, and no getter is provided.

**Comment by alteous** [comment]
Hello,

At the moment almost all extension data is inaccessible from the top-level `gltf` crate. The discussion in #220 and #180 should give some detail why.

Having getters for the json structures is a reasonable request. In the meantime, as a quick and dirty workaround, you could try something like this:

```rust
let document = ...;
let json = document.clone().into_json();
for node in document.nodes() {
    let json_node = json.nodes[node.index()];
    println!("{:#?}", json_node.extensions);
}
```

**Comment by sjohnsonaz** [comment]
Thank you so much.  I'm looking through the `extensions::scene::Node' and `extensions::root::Root` structures, and I can't figure out how to get the light information out of them.  Is it stored somewhere that I'm not seeing?

**Comment by alteous** [comment]
Oops, I failed to realise the extensions struct would be empty. My bad, I keep confusing extensions with extras, sorry! :(

There are a few options from here but none of them are currently implemented:

1. Expose `Extensions` as `serde::RawValue` so you can deserialize yourself. This is how extras are exposed.
2. Implement support for the lights extension, i.e. #227.
3. Implement #227 as well as a hybrid solution that exposes all other extensions as `RawValue`. I have an idea how to do this now:

Currently in `gltf_json` we have:

```rust
struct Material {
    pub extensions: extensions::Material,
    ...
}

mod extensions {
    pub struct Material {
        #[cfg(feature = "KHR_materials_pbrSpecularGlossiness")]
        pub pbr_specular_glossiness: Option<PbrSpecularGlossiness>,
        ...
    }
}
```
The above is designed to match the structure of the input json:

```json
"material": {
    "extensions": {
        "KHR_materials_pbrSpecularGlossiness": {}
    }
}
```

This makes deserialization via. `serde` trivial with `#[derive(Deserialize)]`. We could instead have a two stage deserialization process that's called during `import` or otherwise:

```rust
struct Material {
    pub extensions: serde::RawValue,
    #[cfg(feature = "KHR_materials_pbrSpecularGlossiness")]
    pub pbr_specular_glossiness: Option<PbrSpecularGlossiness>,
}

impl Material {
    fn deserialize_extensions(&mut self) -> serde::Result {
        self.pbr_specular_glossiness = serde::from_str(&self.extensions);
        Ok(())
    }
}
```

**Comment by alteous** [comment]
The [`#[serde(flatten)]`](https://serde.rs/attr-flatten.html) attribute might work here too:

```rust
struct Material {
    #[serde(flatten)]
    pub extensions: HashMap<String, serde::RawValue>,
    #[cfg(feature = "KHR_materials_pbrSpecularGlossiness")]
    pub pbr_specular_glossiness: Option<PbrSpecularGlossiness>,
}

**Comment by alteous** [comment]
Closed in favour of #231. Please try the new support for the `KHR_lights_punctual` extension!

**Comment by sjohnsonaz** [comment]
Everything looks like it's working!  Thank you so much for implementing this so quckly!  Do you know when this might be released to Crates.io?

**Comment by alteous** [comment]
My pleasure. :) I'll release before next week.
