### ISSUE TITLE
how to walk node tree?

### ISSUE THREAD

**Issue by dakom** [gltf-rs/gltf#270]
since `node.children()` returns `Children` instead of `Nodes`, it can't be passed as-is to a recursive function.

What's the recommended approach?

I currently have this, but don't love that it's working over individual elements instead of an Iterator:

```
fn traverse_node_root(gltf:&gltf::Document, node:&gltf::Node) -> Result<(), Error> {
    //do stuff
    for node in node.children() {
        traverse_node_root(gltf, &node)?;
    } 
    Ok(())
};

for node in scene.nodes() {
    traverse_node_root(gltf, &node)?;
} 
```

**Comment by alteous** [comment]
The approach above is the recommended approach. I agree it's a bit awkward but difficult to change without breaking [API guidelines](https://rust-lang.github.io/api-guidelines/).

To avoid overflowing the stack (although I suppose serde has a parsing depth limit anyway) I usually use an explicit stack rather than call functions recursively.

**Comment by dakom** [comment]
Do you mind elaborating a bit more on how to use an explicit stack?

**Comment by alteous** [comment]
Something like this:
```rust
fn walk(node: gltf::Node) {
    let mut stack = vec![node];
    while let Some(node) = stack.pop() {
        process(&node);
        for child in node.children() {
            stack.push(child);
        }
    }
}
```
