### ISSUE TITLE
Make math pub

### ISSUE THREAD

**Issue by dakom** [gltf-rs/gltf#272]
The crate currently has several utility functions in math.rs (which were lifted from cgmath).

If I'm already using `gltf-rs`, and don't need the heavy lifting of full cgmath or nalgebra, I'd end up needing to do pretty much the same thing (have a minimum set of functions to multiply vectors, decompose matrices, etc.) - so it'd be nice to use the `math` module here since it's already built-in.

Don't see how making `math` public would hurt - but could be I'm missing something.

Thoughts?

**Comment by alteous** [comment]
No, I strongly disagree. The aim of the crate is to provide mechanism for importing and, to a lesser extent, exporting glTF. Any internal mathematics is an implementation detail. I wouldn't want to expose such details because it would incur providing some level of backward-compatibility guarantee. What is in the `math` module is the bare minimum required to implement the convenience functions in `Transform`.

**Comment by dakom** [comment]
Ok, closing
