### ISSUE TITLE
Can this crate be used to procedurally generate gLTF files and export as Glb?

### ISSUE THREAD

**Issue by thorlucas** [gltf-rs/gltf#294]
I see some functions for Glb writing to files, but it's rather opaque how I can actually construct a mesh, materials, etc. and write the file (actually I'll want to return the file using Rocket). Additionally all mentions of what this crate does says its for *reading* gLTF files, so it's unclear if this trait is optimized to be able to generate these files.

**Comment by zicklag** [comment]
Yes, you can create gLTF files with this crate and export to Glb. The interesting thing about the gLTF format is that it is essentially just JSON plus binary data and you are responsible for writing out your binary vertex data and specifying the data layout such as vertex attributes and such.

If you want to be able to create gLTF/Glb files with this crate you will first have to understand the gLTF format, which isn't super complicated.

Here is one example of exporting gLTF using this crate:

https://github.com/gltf-rs/gltf/blob/master/examples/export/main.rs

I successfully used this crate to write a Blender gLTF exporter in Rust for [Arsenal](https://github.com/katharostech/arsenal). I had had no previous experience with gLTF, but I was able to follow the great [gLTF Tutorial](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/README.md) and that was all I needed.

**Comment by thorlucas** [comment]
Thank you! I think it would be very beneficial for documentation/README to include some examples of this sort of thing. Once I figure this out I can perhaps try contributing a bit in that regard.

**Comment by zicklag** [comment]
> Once I figure this out I can perhaps try contributing a bit in that regard.

That would be great!

**Comment by clouds56** [comment]
Is there any wrapper for ones to export more easily?
Glance at the example, I think I have to know every detail about glTF formats to successfully construct the mesh (and I still have to make lots of `json::Index::new(0)` which might not be checked)
Ideally there could be API like
```rust
trait Scene {
  add_mesh(&mut self) -> &mut MeshImpl;
  export(&self, output: Output) -> Result<()>;
}

trait Mesh {
  set_position(&mut self, Vec<[f32; 3]>);
  set_uv(&mut self, Vec<[f32; 2]>);
  ...
}
```
if you not prefer have fixed struct like 
```rust
struct Scene {
  meshes: Vec<Mesh>,
  cameras: Vec<Camera>,
  ...
}
struct Mesh {
  positions: Vec<[f32; 3]>,
  uv: Vec<[f32; 2]>,
  ...
}
```
So that people could easily construct meshes **correctly** without knowing every single detail of glTF (remember the 4.54MB large image in README.md?)

FYI, I'm switching from `.obj` to `.glTF` to export meshes since the former doesn't support skins, I would like to export meshes and then load by other tools.
