### ISSUE TITLE
Consider transitioning `gltf-derive` to use `syn@2` instead of `syn@1`

### ISSUE THREAD

**Issue by LikeLakers2** [gltf-rs/gltf#372]
Hi! I noticed that `gltf-derive` (and possibly other parts of this repository) depend on `syn@1`. Perhaps you could consider updating to use `syn@2` wherever possible?

Some things worth noting for anyone who intends to take on this suggestion:
* `syn@2`'s MSRV is Rust 1.56, up from `syn@1`'s Rust 1.31. However, [the repository's README.md](https://github.com/gltf-rs/gltf/blob/69caa857827f534f3f5deade83b37f5b407d79d0/README.md) specifies a MSRV of `Rust 1.32`, so you may wish to also consider if upping `gltf-derive`'s MSRV is okay to do.
* Updating to `syn@2` may not be as simple as swapping the version number - there are a number of breaking changes in `syn@2`, listed at <https://github.com/dtolnay/syn/releases/tag/2.0.0>.

If you do consider to transition to `syn@2`, you have my thanks! :)

**Comment by Elabajaba** [comment]
`syn` 2 is as easy as just changing it from 1 to 2 in cargo.toml, and everything still seems to work in my limited testing.

The current stated msrv is wrong because `image` 0.24.0 has an msrv of 1.56, and `image` 0.24.6 has an msrv of 1.61.

The hard part is that if we're raising the msrv that high, we might as well switch to the 2021 edition, but that breaks compilation. ("trait objects must include the `dyn` keyword" error on the `Validate` macro from `gltf-derive` everywhere it's used in `gltf-json`)
